builders:
  showcase:
    import: 'package:showcase/showcase_generator.dart'
    builder_factories: ['showcaseBuilder']
    build_extensions: {'.dart': ['.showcased.dart']}
    auto_apply: dependents
