version: 2

jobs_defaults: &defaults
  docker:
    - image: cirrusci/flutter
  working_directory: ~/repo

jobs:
  deps:
    <<: *defaults
    steps:
        - checkout
        - run:
            name: Change flutter channel to dev
            command: flutter channel dev
        - run:
            name: Up(down)grade Flutter
            command: ( cd ~/sdks/flutter; git checkout 3581b3ae85d30c5677445e0072c81d1f32280270; cd -; )
        - run:
            name: Download dependencies
            command: flutter packages get
        - save_cache:
            paths:
              - pubspec.lock
              - .packages
              - .dart_tool
              - ~/.pub-cache
            key: v1-pubcache-{{ checksum "pubspec.yaml" }}

  test:
    <<: *defaults
    steps:
        - checkout
        - restore_cache:
            key: v1-pubcache-{{ checksum "pubspec.yaml" }}
        - run:
            name: Change flutter channel to dev
            command: flutter channel dev
        - run:
            name: Up(down)grade Flutter
            command: ( cd ~/sdks/flutter; git checkout 3581b3ae85d30c5677445e0072c81d1f32280270; cd -; )
        - run:
            name: Lint
            command: bash -c '[[ "$(dartfmt -n . | wc -l)" -eq "0" ]]'
        - run:
            name: Dartanalyze
            command: dartanalyzer --fatal-infos --fatal-warnings lib/
        - run:
            name: Test
            command: ( cd example/; flutter test )

  deploy:
    <<: *defaults
    steps:
        - checkout
        - restore_cache:
            key: v1-pubcache-{{ checksum "pubspec.yaml" }}
        - run:
            name: Write credentials
            command: echo "{\"accessToken\":\"$ACCESS_TOKEN\",\"refreshToken\":\"$REFRESH_TOKEN\",\"tokenEndpoint\":\"https://accounts.google.com/o/oauth2/token\",\"scopes\":[\"https://www.googleapis.com/auth/plus.me\",\"https://www.googleapis.com/auth/userinfo.email\"],\"expiration\":$EXPIRATION}" > ~/.pub-cache/credentials.json
        - run:
            name: Deploy to pub.dartlang.org
            command: echo y | pub publish

workflows:
  version: 2
  keep-it-green:
    jobs:
      - deps
      - test:
          requires:
            - deps
  test-and-deploy:
    jobs:
      - deps:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - test:
          requires:
            - deps
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
